// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToledoVault.Data;

#nullable disable

namespace ToledoVault.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "11.0.0-preview.2.26159.112")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToledoVault.Models.AdminCredential", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AdminCredentials");
                });

            modelBuilder.Entity("ToledoVault.Models.Conversation", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("DisappearingTimerSeconds")
                        .HasColumnType("int");

                    b.Property<string>("GroupName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("ToledoVault.Models.ConversationParticipant", b =>
                {
                    b.Property<long>("ConversationId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("ConversationId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ConversationParticipants");
                });

            modelBuilder.Entity("ToledoVault.Models.ConversationReadPointer", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("ConversationId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("LastReadAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("LastReadSequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<int>("UnreadCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("UserId", "ConversationId");

                    b.HasIndex("ConversationId");

                    b.ToTable("ConversationReadPointers");
                });

            modelBuilder.Entity("ToledoVault.Models.Device", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("IdentityPublicKeyClassical")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("IdentityPublicKeyPostQuantum")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<byte[]>("KyberPreKeyPublic")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("KyberPreKeySignature")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("SignedPreKeyId")
                        .HasColumnType("int");

                    b.Property<byte[]>("SignedPreKeyPublic")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("SignedPreKeySignature")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("ToledoVault.Models.EncryptedKeyBackup", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("EncryptedBlob")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varbinary(12)");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varbinary(16)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("EncryptedKeyBackups");
                });

            modelBuilder.Entity("ToledoVault.Models.EncryptedMessage", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Ciphertext")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("ContentType")
                        .HasColumnType("int");

                    b.Property<long>("ConversationId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FileName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsDelivered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("MessageType")
                        .HasColumnType("int");

                    b.Property<string>("MimeType")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long>("RecipientDeviceId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ReplyToMessageId")
                        .HasColumnType("bigint");

                    b.Property<long>("SenderDeviceId")
                        .HasColumnType("bigint");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ServerTimestamp")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("SenderDeviceId");

                    b.HasIndex("ConversationId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("RecipientDeviceId", "IsDelivered");

                    b.ToTable("EncryptedMessages");
                });

            modelBuilder.Entity("ToledoVault.Models.GlobalSetting", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CurrentValue")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DefaultValue")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("ValidationRules")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("GlobalSettings");

                    b.HasData(
                        new
                        {
                            Id = 2375481900587111243L,
                            Category = "Security",
                            CurrentValue = "256",
                            DefaultValue = "256",
                            Description = "AES key size in bits for message encryption",
                            DisplayName = "Encryption Key Length",
                            Key = "security.encryptionKeyLength",
                            LastModifiedAt = new DateTimeOffset(new DateTime(2026, 3, 14, 20, 43, 1, 902, DateTimeKind.Unspecified).AddTicks(5875), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 0,
                            ValidationRules = "{\"options\": [\"128\", \"192\", \"256\"]}",
                            ValueType = "selection"
                        },
                        new
                        {
                            Id = 6767577967081690152L,
                            Category = "Security",
                            CurrentValue = "600000",
                            DefaultValue = "600000",
                            Description = "Number of iterations for password-based key derivation",
                            DisplayName = "PBKDF2 Iterations",
                            Key = "security.pbkdf2Iterations",
                            LastModifiedAt = new DateTimeOffset(new DateTime(2026, 3, 14, 20, 43, 1, 902, DateTimeKind.Unspecified).AddTicks(5875), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 1,
                            ValidationRules = "{\"min\": 100000, \"max\": 1000000}",
                            ValueType = "integer"
                        },
                        new
                        {
                            Id = 4932607441112003257L,
                            Category = "Appearance",
                            CurrentValue = "default",
                            DefaultValue = "default",
                            Description = "Default theme for new users",
                            DisplayName = "Default Theme",
                            Key = "appearance.defaultTheme",
                            LastModifiedAt = new DateTimeOffset(new DateTime(2026, 3, 14, 20, 43, 1, 902, DateTimeKind.Unspecified).AddTicks(5875), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 0,
                            ValidationRules = "{\"options\": [\"default\", \"default-dark\", \"whatsapp\", \"whatsapp-dark\", \"telegram\", \"telegram-dark\", \"signal\", \"signal-dark\"]}",
                            ValueType = "selection"
                        },
                        new
                        {
                            Id = 1647305997828296015L,
                            Category = "Appearance",
                            CurrentValue = "medium",
                            DefaultValue = "medium",
                            Description = "Default font size for new users",
                            DisplayName = "Default Font Size",
                            Key = "appearance.defaultFontSize",
                            LastModifiedAt = new DateTimeOffset(new DateTime(2026, 3, 14, 20, 43, 1, 902, DateTimeKind.Unspecified).AddTicks(5875), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 1,
                            ValidationRules = "{\"options\": [\"small\", \"medium\", \"large\"]}",
                            ValueType = "selection"
                        },
                        new
                        {
                            Id = 3547443041045299879L,
                            Category = "Features",
                            CurrentValue = "true",
                            DefaultValue = "true",
                            Description = "Allow users to see when messages are read",
                            DisplayName = "Read Receipts",
                            Key = "features.readReceipts",
                            LastModifiedAt = new DateTimeOffset(new DateTime(2026, 3, 14, 20, 43, 1, 902, DateTimeKind.Unspecified).AddTicks(5875), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 0,
                            ValueType = "boolean"
                        },
                        new
                        {
                            Id = 8186949666844831051L,
                            Category = "Features",
                            CurrentValue = "true",
                            DefaultValue = "true",
                            Description = "Show when users are typing",
                            DisplayName = "Typing Indicators",
                            Key = "features.typingIndicators",
                            LastModifiedAt = new DateTimeOffset(new DateTime(2026, 3, 14, 20, 43, 1, 902, DateTimeKind.Unspecified).AddTicks(5875), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 1,
                            ValueType = "boolean"
                        },
                        new
                        {
                            Id = 8841052925682027482L,
                            Category = "Features",
                            CurrentValue = "true",
                            DefaultValue = "true",
                            Description = "Generate preview cards for shared URLs",
                            DisplayName = "Link Previews",
                            Key = "features.linkPreviews",
                            LastModifiedAt = new DateTimeOffset(new DateTime(2026, 3, 14, 20, 43, 1, 902, DateTimeKind.Unspecified).AddTicks(5875), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 2,
                            ValueType = "boolean"
                        },
                        new
                        {
                            Id = 6261558502429981551L,
                            Category = "Features",
                            CurrentValue = "true",
                            DefaultValue = "true",
                            Description = "Allow users to send voice messages",
                            DisplayName = "Voice Messages",
                            Key = "features.voiceMessages",
                            LastModifiedAt = new DateTimeOffset(new DateTime(2026, 3, 14, 20, 43, 1, 902, DateTimeKind.Unspecified).AddTicks(5875), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 3,
                            ValueType = "boolean"
                        },
                        new
                        {
                            Id = 5084024938015077971L,
                            Category = "Logging",
                            CurrentValue = "Information",
                            DefaultValue = "Information",
                            Description = "Minimum severity level for log entries",
                            DisplayName = "Minimum Log Level",
                            Key = "logging.minLevel",
                            LastModifiedAt = new DateTimeOffset(new DateTime(2026, 3, 14, 20, 43, 1, 902, DateTimeKind.Unspecified).AddTicks(5875), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 0,
                            ValidationRules = "{\"options\": [\"Verbose\", \"Debug\", \"Information\", \"Warning\", \"Error\", \"Fatal\"]}",
                            ValueType = "selection"
                        },
                        new
                        {
                            Id = 2186619364910816402L,
                            Category = "Logging",
                            CurrentValue = "30",
                            DefaultValue = "30",
                            Description = "Number of days to retain log entries",
                            DisplayName = "Log Retention Days",
                            Key = "logging.retentionDays",
                            LastModifiedAt = new DateTimeOffset(new DateTime(2026, 3, 14, 20, 43, 1, 902, DateTimeKind.Unspecified).AddTicks(5875), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 1,
                            ValidationRules = "{\"min\": 1, \"max\": 365}",
                            ValueType = "integer"
                        },
                        new
                        {
                            Id = 3134461825223462409L,
                            Category = "Notifications",
                            CurrentValue = "3",
                            DefaultValue = "3",
                            Description = "Number of times to retry failed push notifications",
                            DisplayName = "Max Push Notification Retries",
                            Key = "notifications.maxRetries",
                            LastModifiedAt = new DateTimeOffset(new DateTime(2026, 3, 14, 20, 43, 1, 902, DateTimeKind.Unspecified).AddTicks(5875), new TimeSpan(0, 0, 0, 0, 0)),
                            SortOrder = 0,
                            ValidationRules = "{\"min\": 1, \"max\": 10}",
                            ValueType = "integer"
                        });
                });

            modelBuilder.Entity("ToledoVault.Models.LocalizationOverride", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsNewKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ResourceKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("ResourceKey", "LanguageCode")
                        .IsUnique();

                    b.ToTable("LocalizationOverrides");
                });

            modelBuilder.Entity("ToledoVault.Models.MessageReaction", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("MessageId", "UserId", "Emoji")
                        .IsUnique();

                    b.ToTable("MessageReactions");
                });

            modelBuilder.Entity("ToledoVault.Models.OneTimePreKey", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("KeyId")
                        .HasColumnType("int");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "KeyId")
                        .IsUnique();

                    b.ToTable("OneTimePreKeys");
                });

            modelBuilder.Entity("ToledoVault.Models.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("DeviceId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsPersistent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ToledoVault.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletionRequestedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DisplayNameSecondary")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName")
                        .HasDatabaseName("IX_User_DisplayName");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ToledoVault.Models.UserPreferences", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FontSize")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("15");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("en");

                    b.Property<bool>("NotificationsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("ReadReceiptsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("SendPhotoHd")
                        .HasColumnType("bit");

                    b.Property<bool>("SharedKeysEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Theme")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("default");

                    b.Property<bool>("TypingIndicatorsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("ToledoVault.Models.ConversationParticipant", b =>
                {
                    b.HasOne("ToledoVault.Models.Conversation", "Conversation")
                        .WithMany("Participants")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToledoVault.Models.User", "User")
                        .WithMany("ConversationParticipants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToledoVault.Models.ConversationReadPointer", b =>
                {
                    b.HasOne("ToledoVault.Models.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToledoVault.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToledoVault.Models.Device", b =>
                {
                    b.HasOne("ToledoVault.Models.User", "User")
                        .WithMany("Devices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToledoVault.Models.EncryptedKeyBackup", b =>
                {
                    b.HasOne("ToledoVault.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("ToledoVault.Models.EncryptedKeyBackup", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToledoVault.Models.EncryptedMessage", b =>
                {
                    b.HasOne("ToledoVault.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToledoVault.Models.Device", "RecipientDevice")
                        .WithMany()
                        .HasForeignKey("RecipientDeviceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ToledoVault.Models.Device", "SenderDevice")
                        .WithMany()
                        .HasForeignKey("SenderDeviceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("RecipientDevice");

                    b.Navigation("SenderDevice");
                });

            modelBuilder.Entity("ToledoVault.Models.MessageReaction", b =>
                {
                    b.HasOne("ToledoVault.Models.EncryptedMessage", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToledoVault.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToledoVault.Models.OneTimePreKey", b =>
                {
                    b.HasOne("ToledoVault.Models.Device", "Device")
                        .WithMany("OneTimePreKeys")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("ToledoVault.Models.RefreshToken", b =>
                {
                    b.HasOne("ToledoVault.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ToledoVault.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToledoVault.Models.UserPreferences", b =>
                {
                    b.HasOne("ToledoVault.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("ToledoVault.Models.UserPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToledoVault.Models.Conversation", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("ToledoVault.Models.Device", b =>
                {
                    b.Navigation("OneTimePreKeys");
                });

            modelBuilder.Entity("ToledoVault.Models.User", b =>
                {
                    b.Navigation("ConversationParticipants");

                    b.Navigation("Devices");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
